backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    layout: "layouts/blog.astro"
    preview_path: "posts" # Optional: path to the folder where the documents are stored
    label: "Blog" # Used in the UI
    folder: "src/pages/posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/blog.astro" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" } 

  - name: "classifiche" # Used in routes, e.g., /admin/collections/blog
    layout: "layouts/blog.astro"
    preview_path: "posts" # Optional: path to the folder where the documents are stored
    label: "Classifiche" # Used in the UI
    folder: "src/pages/posts/blog/classifiche" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/blog.astro" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Classifica", name: "thumbnail", widget: "File" } 

media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" 
